# Generated by Django 5.1.1 on 2025-01-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_rename_skils_skills_alter_address_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='language_level',
            field=models.CharField(choices=[('BE', 'Beginner'), ('IN', 'Intermediate'), ('AD', 'Advanced'), ('NA', 'Native')], default='BE', max_length=2),
        ),
    ]
