# Generated by Django 5.1.1 on 2025-01-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_languages_language_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree_level',
            field=models.CharField(choices=[('HS', 'High School'), ('AS', "Associate's degree"), ('BA', "Bachelor's degree"), ('MA', "Master's degree"), ('PhD', 'PhD'), ('OT', 'Other')], default='HS', max_length=3),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_level_other',
            field=models.CharField(blank=True, default='N/A', max_length=20, null=True),
        ),
    ]
