# Generated by Django 5.1.1 on 2025-01-30 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_education_degree_level_education_degree_level_other'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='end_work_date',
            new_name='end_studied_date',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='start_work_date',
            new_name='start_studied_date',
        ),
    ]
