# Generated by Django 5.1.1 on 2025-02-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_rename_end_work_date_education_end_studied_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencies',
            name='user',
            field=models.ManyToManyField(to='logic.user'),
        ),
        migrations.AddField(
            model_name='skills',
            name='user',
            field=models.ManyToManyField(to='logic.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
