# Generated by Django 5.1.1 on 2025-02-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0006_competencies_user_skills_user_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=3232, max_length=35, unique=True),
            preserve_default=False,
        ),
    ]
