# Generated by Django 5.1.1 on 2025-02-02 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0008_alter_user_managers_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
