# Generated by Django 5.1.1 on 2025-02-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0009_remove_user_lastname_remove_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
