# Generated by Django 5.1.1 on 2025-02-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0010_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='currently_studying',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='work_experience',
            name='currently_working',
            field=models.BooleanField(default=False),
        ),
    ]
