# Generated by Django 5.1.1 on 2025-02-02 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0011_education_currently_studying_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competencies',
            old_name='name_proficiency',
            new_name='competencies_proficiency',
        ),
    ]
