# Generated by Django 5.1.1 on 2025-02-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0012_rename_name_proficiency_competencies_competencies_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.IntegerField(max_length=11),
        ),
    ]
