# Generated by Django 5.1.1 on 2025-02-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0013_alter_user_cellphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_experience',
            name='job_title',
            field=models.CharField(default=1, max_length=700),
            preserve_default=False,
        ),
    ]
