# Generated by Django 5.1.6 on 2025-02-22 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0014_work_experience_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('determinated', models.BooleanField(default=False)),
                ('primary_color', models.CharField(max_length=50)),
                ('secondary_color', models.CharField(max_length=50)),
                ('accent_color', models.CharField(max_length=50)),
                ('extra_color_1', models.CharField(max_length=50)),
                ('extra_color_2', models.CharField(max_length=50)),
                ('paragraph_size', models.CharField(max_length=50)),
                ('title_size', models.CharField(max_length=50)),
                ('subtitle_size', models.CharField(max_length=50)),
                ('primary_tipography', models.CharField(max_length=50)),
                ('secondary_tipography', models.CharField(max_length=50)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'configuration',
            },
        ),
    ]
