# Generated by Django 5.1.6 on 2025-02-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0015_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.IntegerField(),
        ),
    ]
