# Generated by Django 5.1.6 on 2025-03-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0016_alter_user_cellphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_site',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
