# Generated by Django 5.1.6 on 2025-04-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0017_alter_user_personal_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competencies',
            old_name='name_competencies',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='competencies',
            old_name='competencies_proficiency',
            new_name='proficiency',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='skill_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='skill_proficiency',
            new_name='proficiency',
        ),
    ]
