# Generated by Django 5.1.6 on 2025-04-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0020_alter_image_table_alter_video_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='title', max_length=500),
        ),
    ]
