# Generated by Django 5.1.6 on 2025-04-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0021_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subtitle_srt',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/'),
        ),
        migrations.AddField(
            model_name='video',
            name='subtitle_vtt',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/'),
        ),
    ]
