# Generated by Django 5.1.6 on 2025-04-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0022_video_subtitle_srt_video_subtitle_vtt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='subtitle_srt',
            new_name='subtitle_english',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='subtitle_vtt',
            new_name='subtitle_spanish',
        ),
    ]
