# Generated by Django 5.1.6 on 2025-04-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0023_rename_subtitle_srt_video_subtitle_english_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='file',
            new_name='video',
        ),
    ]
