# Generated by Django 5.1.6 on 2025-04-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0024_rename_file_video_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='video_file',
        ),
    ]
