# Generated by Django 5.1.6 on 2025-04-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0025_rename_video_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_studied_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_studied_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='end_work_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='start_work_date',
            field=models.IntegerField(),
        ),
    ]
