# Generated by Django 5.1.6 on 2025-04-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0027_alter_work_experience_currently_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='currently_studying',
            field=models.BooleanField(default='False', null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree_studied',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_studied_date',
            field=models.IntegerField(null=True),
        ),
    ]
