# Generated by Django 5.1.6 on 2025-04-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0028_alter_education_currently_studying_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
